/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
If you want to view the source, please visit the GitHub repository of this plugin.
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => TasknotesGanttPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian4 = require("obsidian");

// src/settings.ts
var ZOOM_PX_PER_DAY = {
  day: 36,
  week: 12,
  month: 4
};
var DEFAULT_SETTINGS = {
  taskTag: "task",
  taskFolder: "",
  startFields: "scheduled, start, startDate",
  endFields: "due, end, endDate, deadline",
  createdFields: "date created, dateCreated, created",
  completedFields: "completedDate, completed, date modified, dateModified",
  doneStatuses: "done, complete, completed",
  cancelledStatuses: "cancelled, canceled, dropped",
  defaultZoom: "week",
  groupByProject: true,
  showCompleted: true
};
function splitFieldList(value) {
  return value.split(",").map((s) => s.trim()).filter((s) => s.length > 0);
}

// src/settingsTab.ts
var import_obsidian = require("obsidian");
var TasknotesGanttSettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    new import_obsidian.Setting(containerEl).setName("Task tag").setDesc("Frontmatter tag that marks a note as a task (without #).").addText(
      (text) => text.setPlaceholder(DEFAULT_SETTINGS.taskTag).setValue(this.plugin.settings.taskTag).onChange(async (value) => {
        this.plugin.settings.taskTag = value.trim();
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Task folder").setDesc("Only scan notes inside this folder. Leave empty to scan the whole vault.").addText(
      (text) => text.setPlaceholder("e.g. Tasks").setValue(this.plugin.settings.taskFolder).onChange(async (value) => {
        this.plugin.settings.taskFolder = value.trim();
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Date fields").setHeading();
    const fieldSetting = (name, desc, key) => {
      new import_obsidian.Setting(containerEl).setName(name).setDesc(desc + " Comma-separated frontmatter keys, tried in order.").addText(
        (text) => text.setPlaceholder(DEFAULT_SETTINGS[key]).setValue(this.plugin.settings[key]).onChange(async (value) => {
          this.plugin.settings[key] = value;
          await this.plugin.saveSettings();
        })
      );
    };
    fieldSetting("Start date fields", "Where a task's bar begins.", "startFields");
    fieldSetting("End date fields", "Where a task's bar ends (e.g. due date).", "endFields");
    fieldSetting(
      "Created date fields",
      "Fallback start when no start date is set.",
      "createdFields"
    );
    fieldSetting(
      "Completed date fields",
      "Fallback end for done tasks with no end date.",
      "completedFields"
    );
    new import_obsidian.Setting(containerEl).setName("Statuses").setHeading();
    new import_obsidian.Setting(containerEl).setName("Done statuses").setDesc("Comma-separated status values treated as done.").addText(
      (text) => text.setPlaceholder(DEFAULT_SETTINGS.doneStatuses).setValue(this.plugin.settings.doneStatuses).onChange(async (value) => {
        this.plugin.settings.doneStatuses = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Cancelled statuses").setDesc("Comma-separated status values treated as cancelled.").addText(
      (text) => text.setPlaceholder(DEFAULT_SETTINGS.cancelledStatuses).setValue(this.plugin.settings.cancelledStatuses).onChange(async (value) => {
        this.plugin.settings.cancelledStatuses = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("View defaults").setHeading();
    new import_obsidian.Setting(containerEl).setName("Default zoom").addDropdown(
      (dropdown) => dropdown.addOptions({ day: "Day", week: "Week", month: "Month" }).setValue(this.plugin.settings.defaultZoom).onChange(async (value) => {
        this.plugin.settings.defaultZoom = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Group by project").setDesc("Group rows under their first linked project.").addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.groupByProject).onChange(async (value) => {
        this.plugin.settings.groupByProject = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Show completed tasks").addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.showCompleted).onChange(async (value) => {
        this.plugin.settings.showCompleted = value;
        await this.plugin.saveSettings();
      })
    );
  }
};

// src/view.ts
var import_obsidian2 = require("obsidian");

// src/tasks.ts
function startOfDay(d) {
  return new Date(d.getFullYear(), d.getMonth(), d.getDate());
}
function addDays(d, days) {
  return new Date(d.getFullYear(), d.getMonth(), d.getDate() + days);
}
function daysBetween(a, b) {
  return Math.round((startOfDay(b).getTime() - startOfDay(a).getTime()) / 864e5);
}
function parseDate(value) {
  if (value == null) return null;
  const raw = String(value).trim();
  if (!raw) return null;
  const dateOnly = raw.match(/^(\d{4})-(\d{2})-(\d{2})$/);
  if (dateOnly) {
    return new Date(Number(dateOnly[1]), Number(dateOnly[2]) - 1, Number(dateOnly[3]));
  }
  const parsed = new Date(raw);
  if (isNaN(parsed.getTime())) return null;
  return startOfDay(parsed);
}
function firstField(fm, fields) {
  for (const field of fields) {
    if (fm[field] != null && fm[field] !== "") return fm[field];
  }
  return null;
}
function asArray(value) {
  if (value == null) return [];
  if (Array.isArray(value)) return value.map((v) => String(v));
  return [String(value)];
}
function projectDisplayName(raw) {
  let name = raw.trim().replace(/^"+|"+$/g, "");
  const link = name.match(/^\[\[(.+?)\]\]$/);
  if (link) name = link[1];
  const aliasSplit = name.split("|");
  if (aliasSplit.length > 1) return aliasSplit[aliasSplit.length - 1].trim();
  const segments = name.split("/");
  return segments[segments.length - 1].trim();
}
function classifyStatus(status, settings) {
  const s = status.toLowerCase().trim();
  if (!s || s === "open" || s === "todo" || s === "to-do" || s === "none") return "open";
  if (splitFieldList(settings.doneStatuses.toLowerCase()).includes(s)) return "done";
  if (splitFieldList(settings.cancelledStatuses.toLowerCase()).includes(s)) return "cancelled";
  if (s.includes("progress") || s === "doing" || s === "active") return "in-progress";
  return "other";
}
function hasTaskTag(fm, taskTag) {
  var _a;
  const wanted = taskTag.replace(/^#/, "").toLowerCase();
  if (!wanted) return true;
  const tags = asArray((_a = fm["tags"]) != null ? _a : fm["tag"]);
  return tags.some((t) => {
    const tag = t.replace(/^#/, "").toLowerCase();
    return tag === wanted || tag.startsWith(wanted + "/");
  });
}
function collectTasks(app, settings) {
  const folder = settings.taskFolder.replace(/^\/+|\/+$/g, "");
  const tasks = [];
  for (const file of app.vault.getMarkdownFiles()) {
    if (folder && !(file.path === folder || file.path.startsWith(folder + "/"))) continue;
    const task = taskFromFile(app, file, settings, true);
    if (task) tasks.push(task);
  }
  tasks.sort((a, b) => a.start.getTime() - b.start.getTime() || a.title.localeCompare(b.title));
  return tasks;
}
function taskFromFile(app, file, settings, requireTag) {
  var _a, _b, _c, _d, _e, _f;
  const startFields = splitFieldList(settings.startFields);
  const endFields = splitFieldList(settings.endFields);
  const createdFields = splitFieldList(settings.createdFields);
  const completedFields = splitFieldList(settings.completedFields);
  const today = startOfDay(/* @__PURE__ */ new Date());
  const fm = (_a = app.metadataCache.getFileCache(file)) == null ? void 0 : _a.frontmatter;
  if (!fm) return null;
  if (requireTag && !hasTaskTag(fm, settings.taskTag)) return null;
  const status = String((_b = fm["status"]) != null ? _b : "");
  const statusKind = classifyStatus(status, settings);
  let start = parseDate(firstField(fm, startFields));
  let end = parseDate(firstField(fm, endFields));
  let endInferred = false;
  if (!start) start = parseDate(firstField(fm, createdFields));
  if (!end) {
    endInferred = true;
    if (statusKind === "done" || statusKind === "cancelled") {
      end = (_c = parseDate(firstField(fm, completedFields))) != null ? _c : start;
    } else {
      end = today;
    }
  }
  if (!start && end) start = end;
  if (!start || !end) return null;
  if (end < start) end = start;
  return {
    file,
    title: String((_d = fm["title"]) != null ? _d : file.basename),
    status,
    statusKind,
    priority: String((_e = fm["priority"]) != null ? _e : "").replace(/^"+|"+$/g, ""),
    projects: asArray((_f = fm["projects"]) != null ? _f : fm["project"]).map(projectDisplayName),
    start,
    end,
    endInferred
  };
}

// src/render.ts
var NO_PROJECT = "(no project)";
var DEFAULT_COLUMNS = [
  { label: "Task", width: 220, kind: "title", value: (t) => t.title },
  { label: "Status", width: 110, kind: "status", value: (t) => t.status || "open" },
  { label: "Priority", width: 80, kind: "text", value: (t) => t.priority },
  { label: "Start", width: 95, kind: "text", cls: "tg-col-date", value: (t) => formatDate(t.start) },
  { label: "End", width: 95, kind: "text", cls: "tg-col-date", value: (t) => formatDate(t.end) }
];
function formatDate(d) {
  const pad = (n) => String(n).padStart(2, "0");
  return `${d.getFullYear()}-${pad(d.getMonth() + 1)}-${pad(d.getDate())}`;
}
function monthLabel(d) {
  return d.toLocaleDateString(void 0, { month: "short", year: "numeric" });
}
function renderGantt(app, containerEl, allTasks, opts) {
  var _a, _b;
  let tasks = allTasks;
  if (!opts.showCompleted) {
    tasks = tasks.filter((t) => t.statusKind !== "done" && t.statusKind !== "cancelled");
  }
  if (opts.filterText) {
    const needle = opts.filterText.toLowerCase();
    tasks = tasks.filter(
      (t) => t.title.toLowerCase().includes(needle) || t.status.toLowerCase().includes(needle) || t.projects.some((p) => p.toLowerCase().includes(needle))
    );
  }
  let groups;
  if (opts.groupByProject) {
    const byProject = /* @__PURE__ */ new Map();
    for (const t of tasks) {
      const key = (_a = t.projects[0]) != null ? _a : NO_PROJECT;
      const list = (_b = byProject.get(key)) != null ? _b : [];
      list.push(t);
      byProject.set(key, list);
    }
    groups = [...byProject.keys()].sort((a, b) => {
      if (a === NO_PROJECT) return 1;
      if (b === NO_PROJECT) return -1;
      return a.localeCompare(b);
    }).map((name) => ({ name, tasks: byProject.get(name) }));
  } else {
    groups = [{ name: "", tasks }];
  }
  renderGroupedGantt(app, containerEl, groups, {
    pxPerDay: ZOOM_PX_PER_DAY[opts.zoom],
    columns: DEFAULT_COLUMNS
  });
}
function renderGroupedGantt(app, containerEl, groups, opts) {
  containerEl.empty();
  containerEl.addClass("tg-container");
  const tasks = groups.flatMap((g) => g.tasks);
  if (tasks.length === 0) {
    containerEl.createDiv({
      cls: "tg-empty",
      text: "No tasks with usable dates found. Check the filters and the frontmatter field names in the TaskNotes Gantt settings."
    });
    return;
  }
  const { pxPerDay, columns } = opts;
  const metaWidth = columns.reduce((sum, c) => sum + c.width, 0);
  const today = startOfDay(/* @__PURE__ */ new Date());
  let min = tasks[0].start;
  let max = tasks[0].end;
  for (const t of tasks) {
    if (t.start < min) min = t.start;
    if (t.end > max) max = t.end;
  }
  if (today < min) min = today;
  if (today > max) max = today;
  const rangeStart = addDays(min, -3);
  const rangeEnd = addDays(max, 7);
  const totalDays = daysBetween(rangeStart, rangeEnd) + 1;
  const timelineWidth = totalDays * pxPerDay;
  const scroller = containerEl.createDiv({ cls: "tg-scroller" });
  const table = scroller.createDiv({ cls: "tg-table" });
  const header = table.createDiv({ cls: "tg-row tg-header" });
  const headMeta = header.createDiv({ cls: "tg-meta" });
  for (const col of columns) {
    const cell = headMeta.createDiv({ cls: "tg-cell", text: col.label });
    cell.style.width = `${col.width}px`;
  }
  const headTimeline = header.createDiv({ cls: "tg-timeline tg-timeline-header" });
  headTimeline.style.width = `${timelineWidth}px`;
  renderTimeScale(headTimeline, rangeStart, totalDays, pxPerDay);
  for (const group of groups) {
    if (group.name !== "") {
      const groupRow = table.createDiv({ cls: "tg-row tg-group" });
      const groupMeta = groupRow.createDiv({ cls: "tg-meta" });
      groupMeta.style.width = `${metaWidth}px`;
      groupMeta.createDiv({
        cls: "tg-cell tg-group-name",
        text: `${group.name} (${group.tasks.length})`
      });
      groupRow.createDiv({ cls: "tg-timeline" }).style.width = `${timelineWidth}px`;
    }
    for (const task of group.tasks) {
      renderTaskRow(app, table, task, columns, rangeStart, today, pxPerDay, timelineWidth);
    }
  }
}
function renderTimeScale(el, rangeStart, totalDays, pxPerDay) {
  const months = el.createDiv({ cls: "tg-scale-months" });
  const ticks = el.createDiv({ cls: "tg-scale-ticks" });
  let cursor = new Date(rangeStart.getFullYear(), rangeStart.getMonth(), 1);
  const rangeEnd = addDays(rangeStart, totalDays - 1);
  while (cursor <= rangeEnd) {
    const next = new Date(cursor.getFullYear(), cursor.getMonth() + 1, 1);
    const fromDay = Math.max(0, daysBetween(rangeStart, cursor));
    const toDay = Math.min(totalDays, daysBetween(rangeStart, next));
    const label = months.createDiv({ cls: "tg-month", text: monthLabel(cursor) });
    label.style.left = `${fromDay * pxPerDay}px`;
    label.style.width = `${(toDay - fromDay) * pxPerDay}px`;
    cursor = next;
  }
  if (pxPerDay >= 20) {
    for (let i = 0; i < totalDays; i++) {
      const day = addDays(rangeStart, i);
      const tick = ticks.createDiv({ cls: "tg-tick", text: String(day.getDate()) });
      tick.style.left = `${i * pxPerDay}px`;
      tick.style.width = `${pxPerDay}px`;
      if (day.getDay() === 0 || day.getDay() === 6) tick.addClass("tg-weekend");
    }
  } else if (pxPerDay >= 8) {
    for (let i = 0; i < totalDays; i++) {
      const day = addDays(rangeStart, i);
      if (day.getDay() !== 1) continue;
      const tick = ticks.createDiv({ cls: "tg-tick", text: String(day.getDate()) });
      tick.style.left = `${i * pxPerDay}px`;
      tick.style.width = `${7 * pxPerDay}px`;
    }
  }
}
function renderTaskRow(app, table, task, columns, rangeStart, today, pxPerDay, timelineWidth) {
  var _a;
  const row = table.createDiv({ cls: "tg-row tg-task" });
  const meta = row.createDiv({ cls: "tg-meta" });
  for (const col of columns) {
    const cell = meta.createDiv({ cls: `tg-cell${col.cls ? " " + col.cls : ""}` });
    cell.style.width = `${col.width}px`;
    if (col.kind === "title") {
      const link = cell.createEl("a", { cls: "tg-task-link", text: col.value(task) });
      link.addEventListener("click", (evt) => {
        evt.preventDefault();
        app.workspace.openLinkText(task.file.path, "", evt.ctrlKey || evt.metaKey);
      });
    } else if (col.kind === "status") {
      cell.createSpan({
        cls: `tg-status-pill tg-status-${task.statusKind}`,
        text: col.value(task)
      });
    } else {
      cell.setText(col.value(task));
    }
  }
  const timeline = row.createDiv({ cls: "tg-timeline" });
  timeline.style.width = `${timelineWidth}px`;
  const todayLine = timeline.createDiv({ cls: "tg-today" });
  todayLine.style.left = `${(daysBetween(rangeStart, today) + 0.5) * pxPerDay}px`;
  const left = daysBetween(rangeStart, task.start) * pxPerDay;
  const width = Math.max((daysBetween(task.start, task.end) + 1) * pxPerDay, 5);
  const overdue = !task.endInferred && task.statusKind !== "done" && task.statusKind !== "cancelled" && task.end < today;
  const bar = timeline.createDiv({
    cls: `tg-bar tg-status-${task.statusKind}${task.endInferred ? " tg-bar-inferred" : ""}${overdue ? " tg-overdue" : ""}`
  });
  bar.style.left = `${left}px`;
  bar.style.width = `${width}px`;
  bar.setAttr(
    "aria-label",
    `${task.title}
${formatDate(task.start)} \u2192 ${formatDate(task.end)}${task.endInferred ? " (end inferred)" : ""}
Status: ${task.status || "open"}`
  );
  bar.setAttr("title", (_a = bar.getAttr("aria-label")) != null ? _a : "");
  if (width >= 60) {
    bar.createSpan({ cls: "tg-bar-label", text: task.title });
  }
  bar.addEventListener("click", (evt) => {
    app.workspace.openLinkText(task.file.path, "", evt.ctrlKey || evt.metaKey);
  });
}

// src/view.ts
var VIEW_TYPE_TASKNOTES_GANTT = "tasknotes-gantt-view";
var TasknotesGanttView = class extends import_obsidian2.ItemView {
  constructor(leaf, plugin) {
    super(leaf);
    this.chartEl = null;
    this.filterText = "";
    this.plugin = plugin;
    this.zoom = plugin.settings.defaultZoom;
    this.groupByProject = plugin.settings.groupByProject;
    this.showCompleted = plugin.settings.showCompleted;
  }
  getViewType() {
    return VIEW_TYPE_TASKNOTES_GANTT;
  }
  getDisplayText() {
    return "TaskNotes Gantt";
  }
  getIcon() {
    return "gantt-chart";
  }
  async onOpen() {
    const root = this.contentEl;
    root.empty();
    root.addClass("tg-view");
    this.buildToolbar(root.createDiv({ cls: "tg-toolbar" }));
    this.chartEl = root.createDiv({ cls: "tg-chart" });
    this.refresh();
    const delayedRefresh = (0, import_obsidian2.debounce)(() => this.refresh(), 1e3, true);
    this.registerEvent(this.app.metadataCache.on("resolved", delayedRefresh));
    this.registerEvent(this.app.metadataCache.on("changed", delayedRefresh));
    this.registerEvent(this.app.vault.on("delete", delayedRefresh));
    this.registerEvent(this.app.vault.on("rename", delayedRefresh));
  }
  buildToolbar(bar) {
    const filter = bar.createEl("input", {
      cls: "tg-filter",
      attr: { type: "search", placeholder: "Filter tasks\u2026" }
    });
    filter.addEventListener("input", () => {
      this.filterText = filter.value;
      this.refresh();
    });
    const zoomSelect = bar.createEl("select", { cls: "dropdown tg-zoom" });
    for (const level of ["day", "week", "month"]) {
      zoomSelect.createEl("option", {
        text: level.charAt(0).toUpperCase() + level.slice(1),
        attr: { value: level }
      });
    }
    zoomSelect.value = this.zoom;
    zoomSelect.addEventListener("change", () => {
      this.zoom = zoomSelect.value;
      this.refresh();
    });
    const groupToggle = this.makeToggle(bar, "Group by project", this.groupByProject, (v) => {
      this.groupByProject = v;
      this.refresh();
    });
    groupToggle.addClass("tg-toolbar-toggle");
    const doneToggle = this.makeToggle(bar, "Show completed", this.showCompleted, (v) => {
      this.showCompleted = v;
      this.refresh();
    });
    doneToggle.addClass("tg-toolbar-toggle");
    const refreshBtn = bar.createEl("button", { text: "Refresh", cls: "tg-refresh" });
    refreshBtn.addEventListener("click", () => this.refresh());
  }
  makeToggle(parent, label, initial, onChange) {
    const wrapper = parent.createEl("label", { cls: "tg-toggle" });
    const box = wrapper.createEl("input", { attr: { type: "checkbox" } });
    box.checked = initial;
    box.addEventListener("change", () => onChange(box.checked));
    wrapper.createSpan({ text: label });
    return wrapper;
  }
  refresh() {
    if (!this.chartEl) return;
    const tasks = collectTasks(this.app, this.plugin.settings);
    renderGantt(this.app, this.chartEl, tasks, {
      zoom: this.zoom,
      groupByProject: this.groupByProject,
      showCompleted: this.showCompleted,
      filterText: this.filterText
    });
  }
  async onClose() {
    this.chartEl = null;
  }
};

// src/basesView.ts
var import_obsidian3 = require("obsidian");
var GANTT_BASES_VIEW_ID = "tasknotes-gantt";
var GanttBasesView = class extends import_obsidian3.BasesView {
  constructor(controller, containerEl, plugin) {
    super(controller);
    this.type = GANTT_BASES_VIEW_ID;
    this.plugin = plugin;
    this.rootEl = containerEl.createDiv({ cls: "tg-chart tg-bases" });
  }
  onDataUpdated() {
    const settings = this.plugin.settings;
    const groups = [];
    const entryByPath = /* @__PURE__ */ new Map();
    for (const group of this.data.groupedData) {
      const tasks = [];
      for (const entry of group.entries) {
        const task = taskFromFile(this.app, entry.file, settings, false);
        if (!task) continue;
        tasks.push(task);
        entryByPath.set(entry.file.path, entry);
      }
      if (tasks.length === 0) continue;
      groups.push({ name: this.groupLabel(group.key), tasks });
    }
    renderGroupedGantt(this.app, this.rootEl, groups, {
      pxPerDay: ZOOM_PX_PER_DAY[this.zoom()],
      columns: this.buildColumns(entryByPath)
    });
  }
  zoom() {
    const value = this.config.get("zoom");
    if (value === "day" || value === "week" || value === "month") return value;
    return this.plugin.settings.defaultZoom;
  }
  groupLabel(key) {
    if (key == null) return "";
    const text = String(key);
    if (!text || text === "null") return "";
    return /^\[\[.*\]\]$/.test(text) ? projectDisplayName(text) : text;
  }
  /** Title column plus one column per visible property configured on the base. */
  buildColumns(entryByPath) {
    const columns = [DEFAULT_COLUMNS[0]];
    for (const prop of this.config.getOrder()) {
      if (prop === "file.name") continue;
      const label = this.config.getDisplayName(prop);
      const isStatus = prop === "note.status" || label.toLowerCase() === "status";
      columns.push({
        label,
        width: isStatus ? 110 : 120,
        kind: isStatus ? "status" : "text",
        value: (task) => {
          const entry = entryByPath.get(task.file.path);
          const value = entry == null ? void 0 : entry.getValue(prop);
          if (value == null) return "";
          const text = value.toString();
          return /^\[\[.*\]\]$/.test(text) ? projectDisplayName(text) : text;
        }
      });
    }
    if (columns.length === 1) return DEFAULT_COLUMNS;
    return columns;
  }
};
function ganttBasesOptions() {
  return [
    {
      type: "dropdown",
      key: "zoom",
      displayName: "Zoom",
      default: "week",
      options: { day: "Day", week: "Week", month: "Month" }
    }
  ];
}

// src/main.ts
var TasknotesGanttPlugin = class extends import_obsidian4.Plugin {
  constructor() {
    super(...arguments);
    this.settings = DEFAULT_SETTINGS;
  }
  async onload() {
    await this.loadSettings();
    this.registerView(VIEW_TYPE_TASKNOTES_GANTT, (leaf) => new TasknotesGanttView(leaf, this));
    if (typeof this.registerBasesView === "function") {
      this.registerBasesView(GANTT_BASES_VIEW_ID, {
        name: "TaskNotes Gantt",
        icon: "gantt-chart",
        factory: (controller, containerEl) => new GanttBasesView(controller, containerEl, this),
        options: () => ganttBasesOptions()
      });
    }
    this.addRibbonIcon("gantt-chart", "Open TaskNotes Gantt chart", () => {
      void this.activateView();
    });
    this.addCommand({
      id: "open-gantt",
      name: "Open Gantt chart",
      callback: () => void this.activateView()
    });
    this.addSettingTab(new TasknotesGanttSettingTab(this.app, this));
  }
  async activateView() {
    const existing = this.app.workspace.getLeavesOfType(VIEW_TYPE_TASKNOTES_GANTT);
    let leaf;
    if (existing.length > 0) {
      leaf = existing[0];
    } else {
      leaf = this.app.workspace.getLeaf("tab");
      await leaf.setViewState({ type: VIEW_TYPE_TASKNOTES_GANTT, active: true });
    }
    if (leaf) this.app.workspace.revealLeaf(leaf);
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  async saveSettings() {
    await this.saveData(this.settings);
    for (const leaf of this.app.workspace.getLeavesOfType(VIEW_TYPE_TASKNOTES_GANTT)) {
      const view = leaf.view;
      if (view instanceof TasknotesGanttView) view.refresh();
    }
  }
};
