/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
If you want to view the source, please visit the GitHub repository of this plugin.
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => TasknotesGanttPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian4 = require("obsidian");

// src/settings.ts
var ZOOM_PX_PER_DAY = {
  day: 36,
  week: 12,
  month: 4
};
var DEFAULT_SETTINGS = {
  taskTag: "task",
  taskFolder: "",
  startFields: "scheduled, start, startDate",
  endFields: "due, end, endDate, deadline",
  createdFields: "date created, dateCreated, created",
  completedFields: "completedDate, completed, date modified, dateModified",
  doneStatuses: "done, complete, completed",
  cancelledStatuses: "cancelled, canceled, dropped",
  defaultZoom: "week",
  groupByProject: true,
  maxDepth: 3,
  showCompleted: true,
  includeInlineTasks: true
};
function splitFieldList(value) {
  return value.split(",").map((s) => s.trim()).filter((s) => s.length > 0);
}

// src/settingsTab.ts
var import_obsidian = require("obsidian");
var TasknotesGanttSettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    new import_obsidian.Setting(containerEl).setName("Task tag").setDesc("Frontmatter tag that marks a note as a task (without #).").addText(
      (text) => text.setPlaceholder(DEFAULT_SETTINGS.taskTag).setValue(this.plugin.settings.taskTag).onChange(async (value) => {
        this.plugin.settings.taskTag = value.trim();
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Task folder").setDesc("Only scan notes inside this folder. Leave empty to scan the whole vault.").addText(
      (text) => text.setPlaceholder("e.g. Tasks").setValue(this.plugin.settings.taskFolder).onChange(async (value) => {
        this.plugin.settings.taskFolder = value.trim();
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Date fields").setHeading();
    const fieldSetting = (name, desc, key) => {
      new import_obsidian.Setting(containerEl).setName(name).setDesc(desc + " Comma-separated frontmatter keys, tried in order.").addText(
        (text) => text.setPlaceholder(DEFAULT_SETTINGS[key]).setValue(this.plugin.settings[key]).onChange(async (value) => {
          this.plugin.settings[key] = value;
          await this.plugin.saveSettings();
        })
      );
    };
    fieldSetting("Start date fields", "Where a task's bar begins.", "startFields");
    fieldSetting("End date fields", "Where a task's bar ends (e.g. due date).", "endFields");
    fieldSetting(
      "Created date fields",
      "Fallback start when no start date is set.",
      "createdFields"
    );
    fieldSetting(
      "Completed date fields",
      "Fallback end for done tasks with no end date.",
      "completedFields"
    );
    new import_obsidian.Setting(containerEl).setName("Statuses").setHeading();
    new import_obsidian.Setting(containerEl).setName("Done statuses").setDesc("Comma-separated status values treated as done.").addText(
      (text) => text.setPlaceholder(DEFAULT_SETTINGS.doneStatuses).setValue(this.plugin.settings.doneStatuses).onChange(async (value) => {
        this.plugin.settings.doneStatuses = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Cancelled statuses").setDesc("Comma-separated status values treated as cancelled.").addText(
      (text) => text.setPlaceholder(DEFAULT_SETTINGS.cancelledStatuses).setValue(this.plugin.settings.cancelledStatuses).onChange(async (value) => {
        this.plugin.settings.cancelledStatuses = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("View defaults").setHeading();
    new import_obsidian.Setting(containerEl).setName("Default zoom").addDropdown(
      (dropdown) => dropdown.addOptions({ day: "Day", week: "Week", month: "Month" }).setValue(this.plugin.settings.defaultZoom).onChange(async (value) => {
        this.plugin.settings.defaultZoom = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Sub-project depth").setDesc(
      "When the chart is scoped to a parent note, how many levels of sub-projects to follow."
    ).addSlider(
      (slider) => slider.setLimits(1, 6, 1).setDynamicTooltip().setValue(this.plugin.settings.maxDepth).onChange(async (value) => {
        this.plugin.settings.maxDepth = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Group by project").setDesc("Group rows under their first linked project.").addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.groupByProject).onChange(async (value) => {
        this.plugin.settings.groupByProject = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Show completed tasks").addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.showCompleted).onChange(async (value) => {
        this.plugin.settings.showCompleted = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Include inline checkbox tasks").setDesc(
      "In the parent-scoped view, also chart inline '- [ ]' tasks found in note bodies. Dates use Dataview inline fields (e.g. [scheduled:: 2026-06-20] [due:: 2026-06-25]); only tasks with a scheduled/start date are shown."
    ).addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.includeInlineTasks).onChange(async (value) => {
        this.plugin.settings.includeInlineTasks = value;
        await this.plugin.saveSettings();
      })
    );
  }
};

// src/view.ts
var import_obsidian2 = require("obsidian");

// src/tasks.ts
function startOfDay(d) {
  return new Date(d.getFullYear(), d.getMonth(), d.getDate());
}
function addDays(d, days) {
  return new Date(d.getFullYear(), d.getMonth(), d.getDate() + days);
}
function daysBetween(a, b) {
  return Math.round((startOfDay(b).getTime() - startOfDay(a).getTime()) / 864e5);
}
function parseDate(value) {
  if (value == null) return null;
  const raw = String(value).trim();
  if (!raw) return null;
  const dateOnly = raw.match(/^(\d{4})-(\d{2})-(\d{2})$/);
  if (dateOnly) {
    return new Date(Number(dateOnly[1]), Number(dateOnly[2]) - 1, Number(dateOnly[3]));
  }
  const parsed = new Date(raw);
  if (isNaN(parsed.getTime())) return null;
  return startOfDay(parsed);
}
function firstField(fm, fields) {
  for (const field of fields) {
    if (fm[field] != null && fm[field] !== "") return fm[field];
  }
  return null;
}
function asArray(value) {
  if (value == null) return [];
  if (Array.isArray(value)) return value.map((v) => String(v));
  return [String(value)];
}
function extractLinkPath(raw) {
  const name = raw.trim().replace(/^"+|"+$/g, "");
  const link = name.match(/^\[\[(.+?)\]\]$/);
  if (!link) return null;
  return link[1].split("|")[0].split("#")[0].trim();
}
function projectDisplayName(raw) {
  let name = raw.trim().replace(/^"+|"+$/g, "");
  const link = name.match(/^\[\[(.+?)\]\]$/);
  if (link) name = link[1];
  const aliasSplit = name.split("|");
  if (aliasSplit.length > 1) return aliasSplit[aliasSplit.length - 1].trim();
  const segments = name.split("/");
  return segments[segments.length - 1].trim();
}
function classifyStatus(status, settings) {
  const s = status.toLowerCase().trim();
  if (!s || s === "open" || s === "todo" || s === "to-do" || s === "none") return "open";
  if (splitFieldList(settings.doneStatuses.toLowerCase()).includes(s)) return "done";
  if (splitFieldList(settings.cancelledStatuses.toLowerCase()).includes(s)) return "cancelled";
  if (s.includes("progress") || s === "doing" || s === "active") return "in-progress";
  return "other";
}
function hasTaskTag(fm, taskTag) {
  var _a;
  const wanted = taskTag.replace(/^#/, "").toLowerCase();
  if (!wanted) return true;
  const tags = asArray((_a = fm["tags"]) != null ? _a : fm["tag"]);
  return tags.some((t) => {
    const tag = t.replace(/^#/, "").toLowerCase();
    return tag === wanted || tag.startsWith(wanted + "/");
  });
}
function collectTasks(app, settings) {
  const folder = settings.taskFolder.replace(/^\/+|\/+$/g, "");
  const tasks = [];
  for (const file of app.vault.getMarkdownFiles()) {
    if (folder && !(file.path === folder || file.path.startsWith(folder + "/"))) continue;
    const task = taskFromFile(app, file, settings, true);
    if (task) tasks.push(task);
  }
  tasks.sort((a, b) => a.start.getTime() - b.start.getTime() || a.title.localeCompare(b.title));
  return tasks;
}
function taskFromFile(app, file, settings, requireTag) {
  var _a, _b, _c, _d, _e, _f;
  const startFields = splitFieldList(settings.startFields);
  const endFields = splitFieldList(settings.endFields);
  const createdFields = splitFieldList(settings.createdFields);
  const completedFields = splitFieldList(settings.completedFields);
  const today = startOfDay(/* @__PURE__ */ new Date());
  const fm = (_a = app.metadataCache.getFileCache(file)) == null ? void 0 : _a.frontmatter;
  if (!fm) return null;
  if (requireTag && !hasTaskTag(fm, settings.taskTag)) return null;
  const status = String((_b = fm["status"]) != null ? _b : "");
  const statusKind = classifyStatus(status, settings);
  let start = parseDate(firstField(fm, startFields));
  let end = parseDate(firstField(fm, endFields));
  let endInferred = false;
  if (!start) start = parseDate(firstField(fm, createdFields));
  if (!end) {
    endInferred = true;
    if (statusKind === "done" || statusKind === "cancelled") {
      end = (_c = parseDate(firstField(fm, completedFields))) != null ? _c : start;
    } else {
      end = today;
    }
  }
  if (!start && end) start = end;
  if (!start || !end) return null;
  if (end < start) end = start;
  return {
    file,
    title: String((_d = fm["title"]) != null ? _d : file.basename),
    status,
    statusKind,
    priority: String((_e = fm["priority"]) != null ? _e : "").replace(/^"+|"+$/g, ""),
    projects: asArray((_f = fm["projects"]) != null ? _f : fm["project"]).map(projectDisplayName),
    start,
    end,
    endInferred
  };
}
function buildProjectChildrenIndex(app) {
  var _a, _b, _c;
  const childrenOf = /* @__PURE__ */ new Map();
  for (const file of app.vault.getMarkdownFiles()) {
    const fm = (_a = app.metadataCache.getFileCache(file)) == null ? void 0 : _a.frontmatter;
    if (!fm) continue;
    for (const raw of asArray((_b = fm["projects"]) != null ? _b : fm["project"])) {
      const linkpath = extractLinkPath(raw);
      if (!linkpath) continue;
      const dest = app.metadataCache.getFirstLinkpathDest(linkpath, file.path);
      if (!dest) continue;
      const list = (_c = childrenOf.get(dest.path)) != null ? _c : [];
      list.push(file);
      childrenOf.set(dest.path, list);
    }
  }
  return childrenOf;
}
function collectProjectParents(app) {
  const index = buildProjectChildrenIndex(app);
  const parents = [];
  for (const path of index.keys()) {
    const file = app.vault.getAbstractFileByPath(path);
    if (file && "basename" in file) parents.push(file);
  }
  parents.sort((a, b) => a.path.localeCompare(b.path));
  return parents;
}
function collectProjectTree(app, settings, parent, maxDepth) {
  return pruneEmptyGroups(collectProjectTreeRaw(app, settings, parent, maxDepth));
}
function collectProjectTreeRaw(app, settings, parent, maxDepth) {
  const childrenOf = buildProjectChildrenIndex(app);
  const groups = [];
  const expanded = /* @__PURE__ */ new Set();
  const emitted = /* @__PURE__ */ new Set();
  const groupName = (file) => {
    var _a, _b;
    const fm = (_a = app.metadataCache.getFileCache(file)) == null ? void 0 : _a.frontmatter;
    return String((_b = fm == null ? void 0 : fm["title"]) != null ? _b : file.basename);
  };
  const walk = (file, depth) => {
    var _a, _b;
    if (expanded.has(file.path)) return;
    expanded.add(file.path);
    const tasks = [];
    const subProjects = [];
    for (const child of (_a = childrenOf.get(file.path)) != null ? _a : []) {
      const task = taskFromFile(app, child, settings, true);
      if (task && !emitted.has(child.path)) {
        tasks.push(task);
        emitted.add(child.path);
      }
      const hasChildren = ((_b = childrenOf.get(child.path)) != null ? _b : []).length > 0;
      if (hasChildren && depth < maxDepth && !expanded.has(child.path)) {
        subProjects.push(child);
      }
    }
    tasks.sort((a, b) => a.start.getTime() - b.start.getTime() || a.title.localeCompare(b.title));
    groups.push({ name: groupName(file), depth, file, tasks });
    for (const sub of subProjects) walk(sub, depth + 1);
  };
  walk(parent, 0);
  return groups;
}
function statusFromCheckbox(ch) {
  switch (ch) {
    case " ":
      return { status: "open", kind: "open" };
    case "/":
      return { status: "in-progress", kind: "in-progress" };
    case "-":
      return { status: "cancelled", kind: "cancelled" };
    default:
      return { status: "done", kind: "done" };
  }
}
function parseDataviewFields(line) {
  const out = {};
  const re = /[[(]([^[\]()]+?)::\s*([^[\]()]*?)[\])]/g;
  let m;
  while ((m = re.exec(line)) !== null) {
    out[m[1].trim().toLowerCase()] = m[2].trim();
  }
  return out;
}
function inlineTaskTitle(line) {
  return line.replace(/^\s*[-*+]\s+\[.\]\s*/, "").replace(/[[(][^[\]()]+?::\s*[^[\]()]*?[\])]/g, "").replace(/\s{2,}/g, " ").trim();
}
async function collectInlineTasksFromFile(app, settings, file) {
  var _a, _b, _c, _d, _e;
  const items = (_a = app.metadataCache.getFileCache(file)) == null ? void 0 : _a.listItems;
  if (!items) return [];
  const taskItems = items.filter((i) => i.task !== void 0);
  if (taskItems.length === 0) return [];
  const content = await app.vault.cachedRead(file);
  const lines = content.split("\n");
  const startFields = splitFieldList(settings.startFields).map((f) => f.toLowerCase());
  const endFields = splitFieldList(settings.endFields).map((f) => f.toLowerCase());
  const completedFields = splitFieldList(settings.completedFields).map((f) => f.toLowerCase());
  const today = startOfDay(/* @__PURE__ */ new Date());
  const out = [];
  for (const item of taskItems) {
    const lineNo = item.position.start.line;
    const raw = (_b = lines[lineNo]) != null ? _b : "";
    const fields = parseDataviewFields(raw);
    const start = parseDate(firstField(fields, startFields));
    if (!start) continue;
    let { status, kind } = statusFromCheckbox((_c = item.task) != null ? _c : " ");
    if (fields["status"]) {
      status = fields["status"];
      kind = classifyStatus(status, settings);
    }
    let end = parseDate(firstField(fields, endFields));
    let endInferred = false;
    if (!end) {
      endInferred = true;
      end = kind === "done" || kind === "cancelled" ? (_d = parseDate(firstField(fields, completedFields))) != null ? _d : start : today;
    }
    if (end < start) end = start;
    out.push({
      file,
      title: inlineTaskTitle(raw) || "(untitled task)",
      status,
      statusKind: kind,
      priority: (_e = fields["priority"]) != null ? _e : "",
      projects: [],
      start,
      end,
      endInferred,
      kind: "inline",
      line: lineNo,
      indent: 1
    });
  }
  return out;
}
async function augmentGroupsWithInlineTasks(app, settings, groups) {
  const scanned = /* @__PURE__ */ new Set();
  const inlineFor = async (file) => {
    if (scanned.has(file.path)) return [];
    scanned.add(file.path);
    return collectInlineTasksFromFile(app, settings, file);
  };
  const result = [];
  for (const group of groups) {
    const tasks = [];
    if (group.file) tasks.push(...await inlineFor(group.file));
    for (const task of group.tasks) {
      tasks.push(task);
      tasks.push(...await inlineFor(task.file));
    }
    result.push({ ...group, tasks });
  }
  return result;
}
function pruneEmptyGroups(groups) {
  const keep = new Array(groups.length).fill(false);
  for (let i = groups.length - 1; i >= 0; i--) {
    if (groups[i].tasks.length > 0) {
      keep[i] = true;
      continue;
    }
    for (let j = i + 1; j < groups.length && groups[j].depth > groups[i].depth; j++) {
      if (keep[j]) {
        keep[i] = true;
        break;
      }
    }
  }
  return groups.filter((_, i) => keep[i]);
}

// src/tasknotesData.ts
function tasknotesSettings(app) {
  var _a, _b;
  const plugins = (_a = app.plugins) == null ? void 0 : _a.plugins;
  const tn = plugins == null ? void 0 : plugins.tasknotes;
  return (_b = tn == null ? void 0 : tn.settings) != null ? _b : null;
}
function buildStatusColorMap(app) {
  var _a;
  const map = /* @__PURE__ */ new Map();
  const settings = tasknotesSettings(app);
  const statuses = (_a = settings == null ? void 0 : settings.customStatuses) != null ? _a : [];
  for (const st of statuses) {
    if ((st == null ? void 0 : st.value) && (st == null ? void 0 : st.color)) map.set(String(st.value).toLowerCase(), String(st.color));
  }
  return map;
}
var NAME_SYMBOLS = {
  highest: "\u23EB",
  urgent: "\u23EB",
  critical: "\u23EB",
  high: "\u{1F53A}",
  important: "\u{1F53A}",
  medium: "\u{1F538}",
  normal: "\u{1F538}",
  moderate: "\u{1F538}",
  low: "\u{1F53B}",
  lowest: "\u23EC",
  trivial: "\u23EC"
};
var SYMBOL_LADDER = ["\u23EB", "\u{1F53A}", "\u{1F538}", "\u{1F53B}", "\u23EC"];
function buildPriorityMap(app) {
  var _a;
  const map = /* @__PURE__ */ new Map();
  const settings = tasknotesSettings(app);
  const priorities = (_a = settings == null ? void 0 : settings.customPriorities) != null ? _a : [];
  const weights = priorities.map((p) => typeof p.weight === "number" ? p.weight : null).filter((w) => w != null).sort((a, b) => a - b);
  const minW = weights[0];
  const maxW = weights[weights.length - 1];
  for (const p of priorities) {
    if (!(p == null ? void 0 : p.value)) continue;
    const key = String(p.value).toLowerCase();
    let symbol = NAME_SYMBOLS[key];
    if (!symbol && typeof p.weight === "number" && minW != null && maxW != null && maxW > minW) {
      const ratio = (p.weight - minW) / (maxW - minW);
      const idx = Math.round((1 - ratio) * (SYMBOL_LADDER.length - 1));
      symbol = SYMBOL_LADDER[idx];
    }
    map.set(key, { symbol: symbol != null ? symbol : "", color: p.color });
  }
  return map;
}
function priorityVisual(priority, map) {
  var _a;
  const key = priority.toLowerCase().trim();
  if (!key) return { symbol: "" };
  const fromConfig = map.get(key);
  if (fromConfig) return fromConfig;
  return { symbol: (_a = NAME_SYMBOLS[key]) != null ? _a : "" };
}

// src/render.ts
var GROUP_PALETTE = [
  "var(--color-blue)",
  "var(--color-orange)",
  "var(--color-purple)",
  "var(--color-cyan)",
  "var(--color-pink)",
  "var(--color-yellow)",
  "var(--color-green)",
  "var(--color-red)"
];
function assignDepthColors(groups) {
  var _a;
  for (const group of groups) {
    group.color = GROUP_PALETTE[((_a = group.depth) != null ? _a : 0) % GROUP_PALETTE.length];
  }
}
var NO_PROJECT = "(no project)";
var DEFAULT_COLUMNS = [
  { label: "Task", width: 260, kind: "title", value: (t) => t.title }
];
function formatDate(d) {
  const pad = (n) => String(n).padStart(2, "0");
  return `${d.getFullYear()}-${pad(d.getMonth() + 1)}-${pad(d.getDate())}`;
}
function monthLabel(d) {
  return d.toLocaleDateString(void 0, { month: "short", year: "numeric" });
}
function renderGantt(app, containerEl, allTasks, opts) {
  var _a, _b;
  let tasks = allTasks;
  if (!opts.showCompleted) {
    tasks = tasks.filter((t) => t.statusKind !== "done" && t.statusKind !== "cancelled");
  }
  if (opts.filterText) {
    const needle = opts.filterText.toLowerCase();
    tasks = tasks.filter(
      (t) => t.title.toLowerCase().includes(needle) || t.status.toLowerCase().includes(needle) || t.projects.some((p) => p.toLowerCase().includes(needle))
    );
  }
  let groups;
  if (opts.groupByProject) {
    const byProject = /* @__PURE__ */ new Map();
    for (const t of tasks) {
      const key = (_a = t.projects[0]) != null ? _a : NO_PROJECT;
      const list = (_b = byProject.get(key)) != null ? _b : [];
      list.push(t);
      byProject.set(key, list);
    }
    groups = [...byProject.keys()].sort((a, b) => {
      if (a === NO_PROJECT) return 1;
      if (b === NO_PROJECT) return -1;
      return a.localeCompare(b);
    }).map((name) => ({ name, tasks: byProject.get(name) }));
  } else {
    groups = [{ name: "", tasks }];
  }
  renderGroupedGantt(app, containerEl, groups, {
    pxPerDay: ZOOM_PX_PER_DAY[opts.zoom],
    columns: DEFAULT_COLUMNS
  });
}
function renderGroupedGantt(app, containerEl, groups, opts) {
  var _a, _b;
  containerEl.empty();
  containerEl.addClass("tg-container");
  const tasks = groups.flatMap((g) => g.tasks);
  if (tasks.length === 0) {
    containerEl.createDiv({
      cls: "tg-empty",
      text: (_a = opts.emptyText) != null ? _a : "No tasks with usable dates found. Check the filters and the frontmatter field names in the TaskNotes Gantt settings."
    });
    return;
  }
  const { pxPerDay, columns } = opts;
  const metaWidth = columns.reduce((sum, c) => sum + c.width, 0);
  const today = startOfDay(/* @__PURE__ */ new Date());
  const statusColors = buildStatusColorMap(app);
  const priorityMap = buildPriorityMap(app);
  let min = tasks[0].start;
  let max = tasks[0].end;
  for (const t of tasks) {
    if (t.start < min) min = t.start;
    if (t.end > max) max = t.end;
  }
  if (today < min) min = today;
  if (today > max) max = today;
  const rangeStart = addDays(min, -3);
  const rangeEnd = addDays(max, 7);
  const totalDays = daysBetween(rangeStart, rangeEnd) + 1;
  const timelineWidth = totalDays * pxPerDay;
  const scroller = containerEl.createDiv({ cls: "tg-scroller" });
  const table = scroller.createDiv({ cls: "tg-table" });
  const header = table.createDiv({ cls: "tg-row tg-header" });
  const headMeta = header.createDiv({ cls: "tg-meta" });
  for (const col of columns) {
    const cell = headMeta.createDiv({ cls: "tg-cell", text: col.label });
    cell.style.width = `${col.width}px`;
  }
  const headTimeline = header.createDiv({ cls: "tg-timeline tg-timeline-header" });
  headTimeline.style.width = `${timelineWidth}px`;
  renderTimeScale(headTimeline, rangeStart, totalDays, pxPerDay);
  for (const group of groups) {
    if (group.name !== "") {
      const groupRow = table.createDiv({ cls: "tg-row tg-group" });
      const groupMeta = groupRow.createDiv({ cls: "tg-meta" });
      groupMeta.style.width = `${metaWidth}px`;
      const nameCell = groupMeta.createDiv({ cls: "tg-cell tg-group-name" });
      nameCell.style.paddingLeft = `${8 + ((_b = group.depth) != null ? _b : 0) * 20}px`;
      if (group.color) {
        const dot = nameCell.createSpan({ cls: "tg-group-dot" });
        dot.style.background = group.color;
      }
      const label = `${group.name} (${group.tasks.length})`;
      if (group.file) {
        const path = group.file.path;
        const link = nameCell.createEl("a", { cls: "tg-task-link", text: label });
        link.addEventListener("click", (evt) => {
          evt.preventDefault();
          app.workspace.openLinkText(path, "", evt.ctrlKey || evt.metaKey);
        });
      } else {
        nameCell.setText(label);
      }
      groupRow.createDiv({ cls: "tg-timeline" }).style.width = `${timelineWidth}px`;
    }
    for (const task of group.tasks) {
      renderTaskRow(app, table, task, columns, rangeStart, today, pxPerDay, timelineWidth, {
        depthColor: group.color,
        statusColors,
        priorityMap
      });
    }
  }
}
function renderTimeScale(el, rangeStart, totalDays, pxPerDay) {
  const months = el.createDiv({ cls: "tg-scale-months" });
  const ticks = el.createDiv({ cls: "tg-scale-ticks" });
  let cursor = new Date(rangeStart.getFullYear(), rangeStart.getMonth(), 1);
  const rangeEnd = addDays(rangeStart, totalDays - 1);
  while (cursor <= rangeEnd) {
    const next = new Date(cursor.getFullYear(), cursor.getMonth() + 1, 1);
    const fromDay = Math.max(0, daysBetween(rangeStart, cursor));
    const toDay = Math.min(totalDays, daysBetween(rangeStart, next));
    const label = months.createDiv({ cls: "tg-month", text: monthLabel(cursor) });
    label.style.left = `${fromDay * pxPerDay}px`;
    label.style.width = `${(toDay - fromDay) * pxPerDay}px`;
    cursor = next;
  }
  if (pxPerDay >= 20) {
    for (let i = 0; i < totalDays; i++) {
      const day = addDays(rangeStart, i);
      const tick = ticks.createDiv({ cls: "tg-tick", text: String(day.getDate()) });
      tick.style.left = `${i * pxPerDay}px`;
      tick.style.width = `${pxPerDay}px`;
      if (day.getDay() === 0 || day.getDay() === 6) tick.addClass("tg-weekend");
    }
  } else if (pxPerDay >= 8) {
    for (let i = 0; i < totalDays; i++) {
      const day = addDays(rangeStart, i);
      if (day.getDay() !== 1) continue;
      const tick = ticks.createDiv({ cls: "tg-tick", text: String(day.getDate()) });
      tick.style.left = `${i * pxPerDay}px`;
      tick.style.width = `${7 * pxPerDay}px`;
    }
  }
}
function renderTaskRow(app, table, task, columns, rangeStart, today, pxPerDay, timelineWidth, visuals) {
  var _a;
  const row = table.createDiv({ cls: "tg-row tg-task" });
  if (visuals.depthColor) {
    row.addClass("tg-has-depth");
    row.style.setProperty("--tg-depth", visuals.depthColor);
  }
  if (task.kind === "inline") row.addClass("tg-inline");
  const prio = priorityVisual(task.priority, visuals.priorityMap);
  const openTask = (evt) => {
    const mod = evt.ctrlKey || evt.metaKey;
    if (task.kind === "inline" && task.line != null) {
      void app.workspace.getLeaf(mod).openFile(task.file, { eState: { line: task.line } });
    } else {
      app.workspace.openLinkText(task.file.path, "", mod);
    }
  };
  const meta = row.createDiv({ cls: "tg-meta" });
  for (const col of columns) {
    const cell = meta.createDiv({ cls: `tg-cell${col.cls ? " " + col.cls : ""}` });
    cell.style.width = `${col.width}px`;
    if (col.kind === "title") {
      if (task.indent) cell.style.paddingLeft = `${8 + task.indent * 16}px`;
      if (task.kind === "inline") {
        cell.createSpan({ cls: "tg-checkbox", text: checkboxGlyph(task.statusKind) });
      }
      if (prio.symbol) {
        const sym = cell.createSpan({ cls: "tg-prio", text: prio.symbol });
        if (prio.color) sym.style.color = prio.color;
        sym.setAttr("aria-label", `Priority: ${task.priority}`);
        sym.setAttr("title", `Priority: ${task.priority}`);
      }
      const link = cell.createEl("a", { cls: "tg-task-link", text: col.value(task) });
      link.addEventListener("click", (evt) => {
        evt.preventDefault();
        openTask(evt);
      });
    } else if (col.kind === "status") {
      cell.createSpan({
        cls: `tg-status-pill tg-status-${task.statusKind}`,
        text: col.value(task)
      });
    } else {
      cell.setText(col.value(task));
    }
  }
  const timeline = row.createDiv({ cls: "tg-timeline" });
  timeline.style.width = `${timelineWidth}px`;
  const todayLine = timeline.createDiv({ cls: "tg-today" });
  todayLine.style.left = `${(daysBetween(rangeStart, today) + 0.5) * pxPerDay}px`;
  const left = daysBetween(rangeStart, task.start) * pxPerDay;
  const width = Math.max((daysBetween(task.start, task.end) + 1) * pxPerDay, 5);
  const overdue = !task.endInferred && task.statusKind !== "done" && task.statusKind !== "cancelled" && task.end < today;
  const bar = timeline.createDiv({
    cls: `tg-bar tg-status-${task.statusKind}${task.endInferred ? " tg-bar-inferred" : ""}${overdue ? " tg-overdue" : ""}`
  });
  bar.style.left = `${left}px`;
  bar.style.width = `${width}px`;
  const statusColor = visuals.statusColors.get(task.status.toLowerCase());
  if (statusColor) {
    bar.addClass("tg-bar-colored");
    bar.style.background = statusColor;
  }
  bar.setAttr(
    "aria-label",
    `${task.title}
${formatDate(task.start)} \u2192 ${formatDate(task.end)}${task.endInferred ? " (end inferred)" : ""}
Status: ${task.status || "open"}${task.priority ? `
Priority: ${task.priority}` : ""}`
  );
  bar.setAttr("title", (_a = bar.getAttr("aria-label")) != null ? _a : "");
  if (width >= 60) {
    bar.createSpan({ cls: "tg-bar-label", text: task.title });
  }
  bar.addEventListener("click", openTask);
}
function checkboxGlyph(kind) {
  switch (kind) {
    case "done":
      return "\u2611";
    case "cancelled":
      return "\u2612";
    case "in-progress":
      return "\u25D0";
    default:
      return "\u2610";
  }
}

// src/view.ts
var VIEW_TYPE_TASKNOTES_GANTT = "tasknotes-gantt-view";
var TasknotesGanttView = class extends import_obsidian2.ItemView {
  constructor(leaf, plugin) {
    super(leaf);
    this.chartEl = null;
    this.parentChipEl = null;
    this.depthSelectEl = null;
    this.filterText = "";
    this.parentFile = null;
    this.refreshToken = 0;
    this.plugin = plugin;
    this.zoom = plugin.settings.defaultZoom;
    this.groupByProject = plugin.settings.groupByProject;
    this.showCompleted = plugin.settings.showCompleted;
    this.maxDepth = plugin.settings.maxDepth;
    this.includeInlineTasks = plugin.settings.includeInlineTasks;
  }
  getViewType() {
    return VIEW_TYPE_TASKNOTES_GANTT;
  }
  getDisplayText() {
    return "TaskNotes Gantt";
  }
  getIcon() {
    return "gantt-chart";
  }
  async onOpen() {
    const root = this.contentEl;
    root.empty();
    root.addClass("tg-view");
    this.buildToolbar(root.createDiv({ cls: "tg-toolbar" }));
    this.chartEl = root.createDiv({ cls: "tg-chart" });
    this.refresh();
    const delayedRefresh = (0, import_obsidian2.debounce)(() => this.refresh(), 1e3, true);
    this.registerEvent(this.app.metadataCache.on("resolved", delayedRefresh));
    this.registerEvent(this.app.metadataCache.on("changed", delayedRefresh));
    this.registerEvent(this.app.vault.on("delete", delayedRefresh));
    this.registerEvent(this.app.vault.on("rename", delayedRefresh));
  }
  /** Scope the chart to one parent project note (null shows all tasks). */
  setParent(file, depth) {
    this.parentFile = file;
    if (depth != null && Number.isFinite(depth)) {
      this.maxDepth = Math.min(Math.max(Math.floor(depth), 1), 6);
      if (this.depthSelectEl) this.depthSelectEl.value = String(this.maxDepth);
    }
    this.updateParentChip();
    this.refresh();
  }
  buildToolbar(bar) {
    const parentBtn = bar.createEl("button", { text: "Parent note\u2026", cls: "tg-parent-btn" });
    parentBtn.addEventListener("click", () => {
      new ParentNoteModal(this.app, (file) => this.setParent(file)).open();
    });
    this.parentChipEl = bar.createDiv({ cls: "tg-parent-chip" });
    this.updateParentChip();
    const depthSelect = bar.createEl("select", {
      cls: "dropdown tg-depth",
      attr: { "aria-label": "Sub-project depth" }
    });
    for (let depth = 1; depth <= 6; depth++) {
      depthSelect.createEl("option", { text: `Depth ${depth}`, attr: { value: String(depth) } });
    }
    depthSelect.value = String(Math.min(Math.max(this.maxDepth, 1), 6));
    depthSelect.addEventListener("change", () => {
      this.maxDepth = Number(depthSelect.value);
      this.refresh();
    });
    this.depthSelectEl = depthSelect;
    const filter = bar.createEl("input", {
      cls: "tg-filter",
      attr: { type: "search", placeholder: "Filter tasks\u2026" }
    });
    filter.addEventListener("input", () => {
      this.filterText = filter.value;
      this.refresh();
    });
    const zoomSelect = bar.createEl("select", { cls: "dropdown tg-zoom" });
    for (const level of ["day", "week", "month"]) {
      zoomSelect.createEl("option", {
        text: level.charAt(0).toUpperCase() + level.slice(1),
        attr: { value: level }
      });
    }
    zoomSelect.value = this.zoom;
    zoomSelect.addEventListener("change", () => {
      this.zoom = zoomSelect.value;
      this.refresh();
    });
    const groupToggle = this.makeToggle(bar, "Group by project", this.groupByProject, (v) => {
      this.groupByProject = v;
      this.refresh();
    });
    groupToggle.addClass("tg-toolbar-toggle");
    const doneToggle = this.makeToggle(bar, "Show completed", this.showCompleted, (v) => {
      this.showCompleted = v;
      this.refresh();
    });
    doneToggle.addClass("tg-toolbar-toggle");
    const inlineToggle = this.makeToggle(bar, "Inline tasks", this.includeInlineTasks, (v) => {
      this.includeInlineTasks = v;
      this.refresh();
    });
    inlineToggle.addClass("tg-toolbar-toggle");
    inlineToggle.setAttr("aria-label", "Include inline checkbox tasks (parent-scoped view)");
    const refreshBtn = bar.createEl("button", { text: "Refresh", cls: "tg-refresh" });
    refreshBtn.addEventListener("click", () => this.refresh());
  }
  updateParentChip() {
    const chip = this.parentChipEl;
    if (!chip) return;
    chip.empty();
    if (!this.parentFile) {
      chip.createSpan({ cls: "tg-parent-none", text: "All tasks" });
      return;
    }
    chip.createSpan({ cls: "tg-parent-name", text: this.parentFile.basename });
    const clear = chip.createSpan({ cls: "tg-parent-clear", text: "\u2715" });
    clear.setAttr("aria-label", "Clear parent note");
    clear.addEventListener("click", () => this.setParent(null));
  }
  makeToggle(parent, label, initial, onChange) {
    const wrapper = parent.createEl("label", { cls: "tg-toggle" });
    const box = wrapper.createEl("input", { attr: { type: "checkbox" } });
    box.checked = initial;
    box.addEventListener("change", () => onChange(box.checked));
    wrapper.createSpan({ text: label });
    return wrapper;
  }
  matchesFilters(task) {
    if (!this.showCompleted && (task.statusKind === "done" || task.statusKind === "cancelled")) {
      return false;
    }
    if (this.filterText) {
      const needle = this.filterText.toLowerCase();
      return task.title.toLowerCase().includes(needle) || task.status.toLowerCase().includes(needle) || task.projects.some((p) => p.toLowerCase().includes(needle));
    }
    return true;
  }
  refresh() {
    if (!this.chartEl) return;
    if (this.parentFile) {
      void this.refreshParent(this.parentFile);
      return;
    }
    const tasks = collectTasks(this.app, this.plugin.settings);
    renderGantt(this.app, this.chartEl, tasks, {
      zoom: this.zoom,
      groupByProject: this.groupByProject,
      showCompleted: this.showCompleted,
      filterText: this.filterText
    });
  }
  /** Parent-scoped render. Async because inline tasks read note bodies. */
  async refreshParent(parentFile) {
    const token = ++this.refreshToken;
    let groups = collectProjectTreeRaw(this.app, this.plugin.settings, parentFile, this.maxDepth);
    if (this.includeInlineTasks) {
      groups = await augmentGroupsWithInlineTasks(this.app, this.plugin.settings, groups);
    }
    if (token !== this.refreshToken || !this.chartEl) return;
    const filtered = groups.map((group) => ({
      ...group,
      tasks: group.tasks.filter((t) => this.matchesFilters(t))
    }));
    const pruned = pruneEmptyGroups(filtered);
    assignDepthColors(pruned);
    renderGroupedGantt(this.app, this.chartEl, pruned, {
      pxPerDay: ZOOM_PX_PER_DAY[this.zoom],
      columns: DEFAULT_COLUMNS,
      emptyText: `No tasks found under "${parentFile.basename}". Tasks belong to a project when their 'projects' frontmatter links to it (directly or through a sub-project within the depth limit).`
    });
  }
  async onClose() {
    this.chartEl = null;
    this.parentChipEl = null;
    this.depthSelectEl = null;
  }
};
var ParentNoteModal = class extends import_obsidian2.FuzzySuggestModal {
  constructor(app, onChoose) {
    super(app);
    this.onChoose = onChoose;
    this.items = collectProjectParents(app);
    if (this.items.length === 0) this.items = app.vault.getMarkdownFiles();
    this.setPlaceholder("Choose a parent project note\u2026");
  }
  getItems() {
    return this.items;
  }
  getItemText(file) {
    return file.path;
  }
  onChooseItem(file) {
    this.onChoose(file);
  }
};

// src/basesView.ts
var import_obsidian3 = require("obsidian");
var GANTT_BASES_VIEW_ID = "tasknotes-gantt";
var GanttBasesView = class extends import_obsidian3.BasesView {
  constructor(controller, containerEl, plugin) {
    super(controller);
    this.type = GANTT_BASES_VIEW_ID;
    this.plugin = plugin;
    this.rootEl = containerEl.createDiv({ cls: "tg-chart tg-bases" });
  }
  onDataUpdated() {
    const parent = this.parentNote();
    if (parent) {
      this.renderParentScoped(parent);
    } else {
      this.renderGrouped();
    }
  }
  /** Hierarchical mode: walk the parent note's project tree, filtered by the base. */
  renderParentScoped(parent) {
    const allowed = new Set(this.data.data.map((e) => e.file.path));
    const groups = collectProjectTree(
      this.app,
      this.plugin.settings,
      parent,
      this.depth()
    ).map((group) => ({
      ...group,
      tasks: group.tasks.filter((t) => allowed.has(t.file.path))
    }));
    const pruned = pruneEmptyGroups(groups);
    assignDepthColors(pruned);
    renderGroupedGantt(this.app, this.rootEl, pruned, {
      pxPerDay: ZOOM_PX_PER_DAY[this.zoom()],
      columns: DEFAULT_COLUMNS,
      emptyText: `No tasks from this base fall under "${parent.basename}". Tasks belong to a project when their 'projects' frontmatter links to it (directly or through a sub-project within the depth limit).`
    });
  }
  /** Flat mode: one group per the base's group-by value. */
  renderGrouped() {
    const settings = this.plugin.settings;
    const groups = [];
    const entryByPath = /* @__PURE__ */ new Map();
    for (const group of this.data.groupedData) {
      const tasks = [];
      for (const entry of group.entries) {
        const task = taskFromFile(this.app, entry.file, settings, false);
        if (!task) continue;
        tasks.push(task);
        entryByPath.set(entry.file.path, entry);
      }
      if (tasks.length === 0) continue;
      groups.push({ name: this.groupLabel(group.key), tasks });
    }
    renderGroupedGantt(this.app, this.rootEl, groups, {
      pxPerDay: ZOOM_PX_PER_DAY[this.zoom()],
      columns: this.buildColumns(entryByPath)
    });
  }
  parentNote() {
    const value = this.config.get("parentNote");
    if (typeof value !== "string" || !value.trim()) return null;
    const path = value.replace(/^\[\[|\]\]$/g, "").split("|")[0].trim();
    const direct = this.app.vault.getAbstractFileByPath(path);
    if (direct instanceof import_obsidian3.TFile) return direct;
    const resolved = this.app.metadataCache.getFirstLinkpathDest(path, "");
    return resolved instanceof import_obsidian3.TFile ? resolved : null;
  }
  depth() {
    const value = Number(this.config.get("depth"));
    if (Number.isFinite(value) && value >= 1) return Math.min(value, 6);
    return this.plugin.settings.maxDepth;
  }
  zoom() {
    const value = this.config.get("zoom");
    if (value === "day" || value === "week" || value === "month") return value;
    return this.plugin.settings.defaultZoom;
  }
  groupLabel(key) {
    if (key == null) return "";
    const text = String(key);
    if (!text || text === "null") return "";
    return /^\[\[.*\]\]$/.test(text) ? projectDisplayName(text) : text;
  }
  /** Title column plus one column per visible property configured on the base. */
  buildColumns(entryByPath) {
    const columns = [DEFAULT_COLUMNS[0]];
    for (const prop of this.config.getOrder()) {
      if (prop === "file.name") continue;
      const label = this.config.getDisplayName(prop);
      const isStatus = prop === "note.status" || label.toLowerCase() === "status";
      columns.push({
        label,
        width: isStatus ? 110 : 120,
        kind: isStatus ? "status" : "text",
        value: (task) => {
          const entry = entryByPath.get(task.file.path);
          const value = entry == null ? void 0 : entry.getValue(prop);
          if (value == null) return "";
          const text = value.toString();
          return /^\[\[.*\]\]$/.test(text) ? projectDisplayName(text) : text;
        }
      });
    }
    if (columns.length === 1) return DEFAULT_COLUMNS;
    return columns;
  }
};
function ganttBasesOptions() {
  return [
    {
      type: "file",
      key: "parentNote",
      displayName: "Parent note",
      placeholder: "Optional \u2014 scope to a project tree",
      filter: (file) => file.extension === "md"
    },
    {
      type: "dropdown",
      key: "depth",
      displayName: "Sub-project depth",
      default: "3",
      options: { "1": "1", "2": "2", "3": "3", "4": "4", "5": "5", "6": "6" }
    },
    {
      type: "dropdown",
      key: "zoom",
      displayName: "Zoom",
      default: "week",
      options: { day: "Day", week: "Week", month: "Month" }
    }
  ];
}

// src/main.ts
var TasknotesGanttPlugin = class extends import_obsidian4.Plugin {
  constructor() {
    super(...arguments);
    this.settings = DEFAULT_SETTINGS;
  }
  async onload() {
    await this.loadSettings();
    this.registerView(VIEW_TYPE_TASKNOTES_GANTT, (leaf) => new TasknotesGanttView(leaf, this));
    if (typeof this.registerBasesView === "function") {
      this.registerBasesView(GANTT_BASES_VIEW_ID, {
        name: "TaskNotes Gantt",
        icon: "gantt-chart",
        factory: (controller, containerEl) => new GanttBasesView(controller, containerEl, this),
        options: () => ganttBasesOptions()
      });
    }
    this.addRibbonIcon("gantt-chart", "Open TaskNotes Gantt chart", () => {
      void this.activateView();
    });
    this.addCommand({
      id: "open-gantt",
      name: "Open Gantt chart",
      callback: () => void this.activateView()
    });
    this.addCommand({
      id: "open-gantt-for-current-note",
      name: "Open Gantt chart for current note (as parent project)",
      callback: async () => {
        const file = this.app.workspace.getActiveFile();
        const view = await this.activateView();
        if (view && file) view.setParent(file);
      }
    });
    this.addCommand({
      id: "copy-gantt-link",
      name: "Copy Gantt chart link for current note (as parent project)",
      checkCallback: (checking) => {
        const file = this.app.workspace.getActiveFile();
        if (!file) return false;
        if (!checking) {
          void navigator.clipboard.writeText(this.buildGanttUri(file));
          new import_obsidian4.Notice("TaskNotes Gantt: link copied to clipboard");
        }
        return true;
      }
    });
    this.registerObsidianProtocolHandler("tasknotes-gantt", async (params) => {
      var _a, _b;
      const activeBefore = this.app.workspace.getActiveFile();
      const view = await this.activateView();
      if (!view) return;
      const parentName = ((_b = (_a = params.parent) != null ? _a : params.parentNote) != null ? _b : "").trim();
      let file;
      if (parentName) {
        file = this.resolveNote(parentName);
        if (!file) {
          new import_obsidian4.Notice(`TaskNotes Gantt: note "${parentName}" not found`);
          return;
        }
      } else {
        file = activeBefore;
        if (!file) return;
      }
      const depth = params.depth ? Number(params.depth) : void 0;
      view.setParent(file, depth);
    });
    this.addSettingTab(new TasknotesGanttSettingTab(this.app, this));
  }
  /** Resolve a note name, wikilink, or path to a TFile (null if not found). */
  resolveNote(name) {
    const cleaned = name.replace(/^\[\[|\]\]$/g, "").split("|")[0].trim();
    const byLink = this.app.metadataCache.getFirstLinkpathDest(cleaned, "");
    if (byLink instanceof import_obsidian4.TFile) return byLink;
    const byPath = this.app.vault.getAbstractFileByPath(cleaned);
    return byPath instanceof import_obsidian4.TFile ? byPath : null;
  }
  /** Build an obsidian:// link that opens this view scoped to the given note. */
  buildGanttUri(file) {
    const vault = encodeURIComponent(this.app.vault.getName());
    const parent = encodeURIComponent(file.basename);
    return `obsidian://tasknotes-gantt?vault=${vault}&parent=${parent}`;
  }
  async activateView() {
    const existing = this.app.workspace.getLeavesOfType(VIEW_TYPE_TASKNOTES_GANTT);
    let leaf;
    if (existing.length > 0) {
      leaf = existing[0];
    } else {
      leaf = this.app.workspace.getLeaf("tab");
      await leaf.setViewState({ type: VIEW_TYPE_TASKNOTES_GANTT, active: true });
    }
    if (!leaf) return null;
    await this.app.workspace.revealLeaf(leaf);
    this.app.workspace.setActiveLeaf(leaf, { focus: true });
    return leaf.view instanceof TasknotesGanttView ? leaf.view : null;
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  async saveSettings() {
    await this.saveData(this.settings);
    for (const leaf of this.app.workspace.getLeavesOfType(VIEW_TYPE_TASKNOTES_GANTT)) {
      const view = leaf.view;
      if (view instanceof TasknotesGanttView) view.refresh();
    }
  }
};
